<script setup lang="ts">
import {ref,watch} from 'vue';import {RouterLink} from 'vue-router';import {fetchCircle,fetchCirclePosts,type PublicCircle} from '@/services/circle';import type {CommunityPost} from '@/types/community'
import {absoluteSeoUrl,toSeoDescription,useSeoMeta} from '@/composables/useSeoMeta'
const props=defineProps<{circleId:number}>(),circle=ref<PublicCircle|null>(null),posts=ref<CommunityPost[]>([]),error=ref('');let requestSequence=0
watch(()=>props.circleId,async(circleId)=>{const request=++requestSequence;circle.value=null;posts.value=[];error.value='';try{const[detail,page]=await Promise.all([fetchCircle(circleId),fetchCirclePosts(circleId)]);if(request!==requestSequence)return;circle.value=detail;posts.value=page.list}catch(e){if(request===requestSequence)error.value=e instanceof Error?e.message:'圈子加载失败'}},{immediate:true})
useSeoMeta(()=>{const path=`/groups/${props.circleId}`,current=circle.value;if(!current)return{title:'圈子详情',description:'查看官方圈子资料和公开帖子。',canonical:path,robots:'noindex,nofollow'};return{title:current.name,description:current.description,canonical:path,image:current.coverUrl||undefined,jsonLd:{'@context':'https://schema.org','@type':'CollectionPage',name:current.name,description:current.description,url:absoluteSeoUrl(path),about:{'@type':'Organization',name:current.name},mainEntity:{'@type':'ItemList',itemListElement:posts.value.map((post,index)=>({'@type':'ListItem',position:index+1,name:post.title,url:absoluteSeoUrl(`/community/posts/${post.id}`),description:toSeoDescription(post.content)}))}}}})
</script>
<template><section class="page-section"><p v-if="error" class="feedback is-error">{{error}}</p><template v-if="circle"><header class="circle-hero"><p class="eyebrow">{{circle.region}} · 官方圈子</p><h1>{{circle.name}}</h1><p>{{circle.description}}</p><strong>{{circle.memberCount}} 位成员 · {{circle.postCount}} 篇帖子</strong></header><div class="rank-list"><article v-for="post in posts" :key="post.id" class="content-card rank-item"><div class="rank-item__body"><p class="eyebrow name-with-badge"><RouterLink :to="`/users/${post.userId}`">{{post.userName}}</RouterLink><span v-if="post.authorCertification" class="verified-badge verified-badge--compact">{{post.authorCertification.label}}</span><span>· {{post.createdAt}}</span></p><h2><RouterLink :to="`/community/posts/${post.id}`">{{post.title}}</RouterLink></h2><p>{{post.content}}</p><small>喜欢 {{post.likeCount}} · 评论 {{post.commentCount}}</small></div></article></div></template></section></template>
<style scoped>.circle-hero{padding:34px;border-radius:30px;background:linear-gradient(135deg,#ffe4d4,#fff9f4);box-shadow:0 18px 44px rgba(90,45,24,.1);margin-bottom:24px}.circle-hero h1{font-size:38px;margin:8px 0}.circle-hero strong{font-variant-numeric:tabular-nums}</style>
