<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { createAppealDraft, fetchReviews, saveAppeal, saveReply, submitAppeal } from '@/services/merchant'
const loading = ref(true); const error = ref(''); const items = ref<Record<string, unknown>[]>([]); const replyDrafts = ref<Record<number, string>>({}); const appealReasons = ref<Record<number, string>>({})
async function load() { loading.value = true; try { items.value = (await fetchReviews({ page: 1, pageSize: 50 })).list } catch (e) { error.value = e instanceof Error ? e.message : '加载失败' } finally { loading.value = false } }
async function reply(item: Record<string, unknown>) { try { await saveReply(Number(item.id), replyDrafts.value[Number(item.id)] ?? String(item.merchantReply ?? '')); await load() } catch (e) { error.value = e instanceof Error ? e.message : '回复失败' } }
async function appeal(item: Record<string, unknown>) { try { const reviewId = Number(item.id); const reason = (appealReasons.value[reviewId] ?? '').trim(); if (reason.length < 10) { error.value = '申诉理由至少 10 个字。'; return } const draft = await createAppealDraft(reviewId); if (typeof draft.id === 'number') { await saveAppeal(draft.id, { reason, evidenceUrls: [] }); await submitAppeal(draft.id) } appealReasons.value[reviewId] = ''; await load() } catch (e) { error.value = e instanceof Error ? e.message : '申诉失败' } }
onMounted(load)
</script>
<template><div class="toolbar"><button @click="load">刷新</button></div><p v-if="loading" class="muted">加载中...</p><p v-if="error" class="error">{{ error }}</p><table v-if="!loading" class="table"><thead><tr><th>用户</th><th>评分</th><th>内容</th><th>商家回复</th><th>申诉理由</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="String(item.id)"><td>{{ item.userNickname ?? item.userName }}</td><td>{{ item.score }}</td><td>{{ item.content }}</td><td><textarea v-model="replyDrafts[Number(item.id)]" :placeholder="String(item.merchantReply ?? '输入回复')" rows="2" /></td><td><textarea v-model="appealReasons[Number(item.id)]" placeholder="至少 10 个字，说明恶意或失实点" rows="2" /></td><td><button @click="reply(item)">保存回复</button><button @click="appeal(item)">提交申诉</button></td></tr></tbody></table></template>
