package com.tuowei.dazhongdianping.module.trade.service;
import com.tuowei.dazhongdianping.common.api.*;import com.tuowei.dazhongdianping.common.region.RegionContext;import com.tuowei.dazhongdianping.common.user.*;import com.tuowei.dazhongdianping.module.auth.service.UserGrowthService;import com.tuowei.dazhongdianping.module.trade.mapper.TradeMapper;import com.tuowei.dazhongdianping.module.trade.model.*;import com.tuowei.dazhongdianping.module.trade.model.request.*;import java.math.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class TradeService {
 private final TradeMapper mapper;private final UserGrowthService userGrowthService;private final String secret;private final boolean mockEnabled;public TradeService(TradeMapper mapper,UserGrowthService userGrowthService,@Value("${app.payment.notify-secret:local-payment-notify-secret}")String secret,@Value("${app.payment.mock-enabled:true}")boolean mockEnabled){this.mapper=mapper;this.userGrowthService=userGrowthService;this.secret=secret;this.mockEnabled=mockEnabled;}
 public List<Map<String,Object>> shopDeals(Long shopId){return mapper.selectShopDeals(shopId,region()).stream().map(this::dealSummary).toList();}
 public Map<String,Object> deal(Long id){DealRow d=requireDeal(id);Map<String,Object> m=new LinkedHashMap<>(dealSummary(d));m.put("items",mapper.selectDealItems(id));m.put("rules",d.getRules());m.put("validStart",d.getValidStart());m.put("validEnd",d.getValidEnd());return m;}
 @Transactional public Map<String,Object> createOrder(OrderCreateRequest req){UserSession u=user();DealRow d=requireDeal(req.dealId());if(d.getValidEnd()!=null&&d.getValidEnd().isBefore(LocalDate.now()))throw new IllegalArgumentException("团购已过期");if(mapper.decrementDealStock(d.getId(),req.quantity())==0)throw new IllegalArgumentException("团购库存不足");OrderRow o=new OrderRow();o.setOrderNo("OD"+System.currentTimeMillis()+String.format("%04d",new Random().nextInt(10000)));o.setUserId(u.userId());o.setDealId(d.getId());o.setShopId(d.getShopId());o.setRegion(d.getRegion());o.setQuantity(req.quantity());o.setUnitPrice(d.getPrice());o.setAmount(d.getPrice().multiply(BigDecimal.valueOf(req.quantity())).setScale(2));o.setCurrency(d.getCurrency());o.setExpireAt(LocalDateTime.now().plusMinutes(30));mapper.insertOrder(o);return orderMap(requireOrder(o.getId()),false);}
 public PageResult<Map<String,Object>> orders(Integer payStatus,Integer page,Integer pageSize){int p=page==null?1:Math.max(1,page),s=pageSize==null?12:Math.min(50,Math.max(1,pageSize));UserSession u=user();long total=mapper.countUserOrders(u.userId(),region(),payStatus);List<Map<String,Object>> list=mapper.selectUserOrders(u.userId(),region(),payStatus,s,(p-1)*s).stream().map(o->orderMap(o,false)).toList();return new PageResult<>(list,total,p,s,(p-1)*s+list.size()<total);}
 public Map<String,Object> order(Long id){return orderMap(requireOrder(id),true);}
 @Transactional public Map<String,Object> pay(Long id){OrderRow o=requireOrder(id);if(o.getStatus()!=1||o.getPayStatus()!=0)throw new IllegalArgumentException("订单当前不可支付");PaymentRow p=mapper.selectPayment(id);if(p==null){p=new PaymentRow();p.setOrderId(id);p.setOrderNo(o.getOrderNo());p.setChannel("CN".equals(o.getRegion())?"alipay_mock":"stripe_mock");p.setChannelTxn("TX"+UUID.randomUUID().toString().replace("-","").substring(0,24));p.setAmount(o.getAmount());p.setCurrency(o.getCurrency());mapper.insertPayment(p);}return Map.of("paymentId",p.getId(),"channel",p.getChannel(),"channelTxn",p.getChannelTxn(),"orderNo",o.getOrderNo(),"amount",o.getAmount(),"currency",o.getCurrency());}
 @Transactional public Map<String,Object> notify(String channel,PaymentNotifyRequest req){if(!sign(req.orderNo(),req.channelTxn(),req.status(),req.amount()).equalsIgnoreCase(req.signature()))throw new IllegalArgumentException("支付回调签名非法");PaymentRow p=mapper.selectPaymentByTxn(channel,req.channelTxn());if(p==null||!p.getOrderNo().equals(req.orderNo()))throw new NotFoundException("支付流水不存在");OrderRow o=mapper.selectOrderByNo(req.orderNo());if(o==null||o.getAmount().compareTo(req.amount())!=0)throw new IllegalArgumentException("支付金额不一致");if(p.getStatus()==1)return Map.of("processed",false,"orderNo",o.getOrderNo());if(!"SUCCESS".equalsIgnoreCase(req.status()))throw new IllegalArgumentException("支付未成功");p.setRawResponse(req.toString());mapper.markPaymentSuccess(p);if(mapper.markOrderPaid(o.getId(),channel)==1){userGrowthService.rewardForCompletedOrder(o.getUserId(),o.getId());if(mapper.countOrderCoupons(o.getId())==0){DealRow d=mapper.selectDeal(o.getDealId(),o.getRegion());for(int i=0;i<o.getQuantity();i++){CouponRow c=new CouponRow();c.setOrderId(o.getId());c.setUserId(o.getUserId());c.setDealId(o.getDealId());c.setShopId(o.getShopId());c.setCode("CP"+UUID.randomUUID().toString().replace("-","").substring(0,20).toUpperCase());c.setExpireAt(d.getValidEnd());mapper.insertCoupon(c);}}}return Map.of("processed",true,"orderNo",o.getOrderNo());}
 @Transactional public Map<String,Object> completeMockPayment(Long id){if(!mockEnabled)throw new IllegalArgumentException("模拟支付未启用");OrderRow o=requireOrder(id);Map<String,Object> intent=pay(id);String channel=(String)intent.get("channel");if(!channel.endsWith("_mock"))throw new IllegalArgumentException("当前渠道不是模拟支付");String txn=(String)intent.get("channelTxn");notify(channel,new PaymentNotifyRequest(o.getOrderNo(),txn,"SUCCESS",o.getAmount(),sign(o.getOrderNo(),txn,"SUCCESS",o.getAmount())));return orderMap(requireOrder(id),true);}
 @Transactional public Map<String,Object> cancel(Long id){OrderRow o=requireOrder(id);if(mapper.closeOrder(id,o.getUserId())==0)throw new IllegalArgumentException("订单当前不可取消");mapper.restoreDealStock(o.getDealId(),o.getQuantity());return orderMap(requireOrder(id),false);}
 @Transactional public Map<String,Object> refund(Long id,RefundRequest req){OrderRow o=requireOrder(id);if(o.getPayStatus()!=1||o.getStatus()!=1)throw new IllegalArgumentException("订单当前不可退款");if(mapper.countUsedCoupons(id)>0)throw new IllegalArgumentException("存在已核销券，不能整单退款");if(mapper.selectRefundByOrder(id)!=null)throw new IllegalArgumentException("订单已有退款申请");mapper.insertRefund(id,o.getAmount(),req.reason().trim());return orderMap(requireOrder(id),true);}
 public PageResult<Map<String,Object>> coupons(Integer status,Integer page,Integer pageSize){int p=page==null?1:Math.max(1,page),s=pageSize==null?12:Math.min(50,Math.max(1,pageSize));UserSession u=user();long total=mapper.countCoupons(u.userId(),region(),status);List<Map<String,Object>> list=mapper.selectCoupons(u.userId(),region(),status,s,(p-1)*s).stream().map(this::couponMap).toList();return new PageResult<>(list,total,p,s,(p-1)*s+list.size()<total);}
 private DealRow requireDeal(Long id){DealRow d=mapper.selectDeal(id,region());if(d==null)throw new NotFoundException("团购不存在");return d;}private OrderRow requireOrder(Long id){UserSession u=user();OrderRow o=mapper.selectUserOrder(id,u.userId(),region());if(o==null)throw new NotFoundException("订单不存在");return o;}private UserSession user(){UserSession u=UserSessionContext.get();if(u==null)throw new UnauthorizedException("用户登录状态不存在");return u;}private String region(){return RegionContext.getRegion().name();}
 private Map<String,Object> dealSummary(DealRow d){Map<String,Object>m=new LinkedHashMap<>();m.put("id",d.getId());m.put("shopId",d.getShopId());m.put("shopName",d.getShopName());m.put("title",d.getTitle());m.put("coverImage",d.getCoverImage());m.put("price",d.getPrice());m.put("originalPrice",d.getOriginalPrice());m.put("currency",d.getCurrency());m.put("stock",d.getStock());m.put("soldCount",d.getSoldCount());return m;}
 private Map<String,Object> orderMap(OrderRow o,boolean includeCoupons){Map<String,Object>m=new LinkedHashMap<>();m.put("id",o.getId());m.put("orderNo",o.getOrderNo());m.put("dealId",o.getDealId());m.put("dealTitle",o.getDealTitle());m.put("shopId",o.getShopId());m.put("shopName",o.getShopName());m.put("coverImage",o.getCoverImage());m.put("quantity",o.getQuantity());m.put("unitPrice",o.getUnitPrice());m.put("amount",o.getAmount());m.put("currency",o.getCurrency());m.put("payStatus",o.getPayStatus());m.put("payStatusText",switch(o.getPayStatus()){case 1->"已支付";case 2->"已退款";case 3->"部分退款";default->"待支付";});m.put("status",o.getStatus());RefundRow refund=mapper.selectRefundByOrder(o.getId());if(refund!=null)m.put("refund",refundMap(refund));if(includeCoupons)m.put("coupons",mapper.selectOrderCoupons(o.getId(),o.getUserId()).stream().map(this::couponMap).toList());return m;}
 private Map<String,Object> refundMap(RefundRow r){Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getId());m.put("amount",r.getAmount());m.put("reason",r.getReason());m.put("status",r.getStatus());m.put("statusText",switch(r.getStatus()){case 1->"退款成功";case 2->"已驳回";default->"申请中";});m.put("auditReason",r.getAuditReason());m.put("auditedAt",r.getAuditedAt());m.put("createdAt",r.getCreatedAt());return m;}
 private Map<String,Object> couponMap(CouponRow c){Map<String,Object>m=new LinkedHashMap<>();m.put("id",c.getId());m.put("orderId",c.getOrderId());m.put("code",c.getCode());m.put("status",c.getStatus());m.put("statusText",switch(c.getStatus()){case 2->"已使用";case 3->"已过期";case 4->"已退款";default->"待使用";});m.put("dealId",c.getDealId());m.put("dealTitle",c.getDealTitle());m.put("shopId",c.getShopId());m.put("shopName",c.getShopName());m.put("coverImage",c.getCoverImage());m.put("expireAt",c.getExpireAt());return m;}
 private String sign(String orderNo,String txn,String status,BigDecimal amount){try{String raw=orderNo+"|"+txn+"|"+status+"|"+amount.setScale(2).toPlainString()+"|"+secret;return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
