package com.tuowei.dazhongdianping.module.reservation.service;
import com.tuowei.dazhongdianping.common.api.*;import com.tuowei.dazhongdianping.common.region.RegionContext;import com.tuowei.dazhongdianping.common.user.*;import com.tuowei.dazhongdianping.module.notification.service.NotificationService;import com.tuowei.dazhongdianping.module.reservation.mapper.ReservationMapper;import com.tuowei.dazhongdianping.module.reservation.model.*;import com.tuowei.dazhongdianping.module.reservation.model.request.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class ReservationService{
 private static final String RESERVATION_CREATED_TYPE = "reservation.created";
 private static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
 private final ReservationMapper mapper;private final NotificationService notificationService;public ReservationService(ReservationMapper mapper,NotificationService notificationService){this.mapper=mapper;this.notificationService=notificationService;}
 public Map<String,Object> slots(Long shopId,LocalDate date,Integer people){if(people==null||people<1)throw new IllegalArgumentException("peopleCount 必须大于 0");List<Map<String,Object>> list=mapper.selectSlots(shopId,region(),date).stream().map(s->slotMap(s,people)).toList();Map<String,Object> result=new LinkedHashMap<>();result.put("shop",list.isEmpty()?Map.of("id",shopId):Map.of("id",shopId,"name",mapper.selectSlots(shopId,region(),date).get(0).getShopName()));result.put("date",date);result.put("list",list);return result;}
 @Transactional public Map<String,Object> create(ReservationCreateRequest req){UserSession u=user();if(req.slotId()==null&&req.reserveTime()==null)throw new IllegalArgumentException("slotId 与 reserveTime 至少传一个");ReservationSlotRow slot=req.slotId()==null?null:requireSlot(req.slotId(),req.shopId());LocalDateTime time=slot==null?req.reserveTime():LocalDateTime.of(slot.getBizDate(),slot.getStartTime());if(slot!=null&&mapper.reserveCapacity(slot.getId(),req.peopleCount())==0)throw new IllegalArgumentException("当前时段余量不足");ReservationRow r=new ReservationRow();r.setReservationNo("RS"+System.currentTimeMillis()+String.format("%04d",new Random().nextInt(10000)));r.setUserId(u.userId());r.setShopId(req.shopId());r.setSlotId(slot==null?0L:slot.getId());r.setRegion(region());r.setReserveTime(time);r.setPeopleCount(req.peopleCount());r.setContactName(req.contactName().trim());r.setContactPhone(req.contactPhone().trim());r.setRemark(req.remark()==null?"":req.remark().trim());r.setStatus(slot!=null&&slot.getConfirmMode()==1?1:0);mapper.insertReservation(r);log(r.getId(),1,0,r.getStatus(),null,time,"创建预订",u.userId());ReservationRow created=require(r.getId());notifyReservationCreated(created);return map(created,false);}
 public PageResult<Map<String,Object>> list(Integer status,Integer page,Integer pageSize){int p=page==null?1:Math.max(1,page),s=pageSize==null?12:Math.min(50,Math.max(1,pageSize));UserSession u=user();long total=mapper.countUserReservations(u.userId(),region(),status);List<Map<String,Object>> list=mapper.selectUserReservations(u.userId(),region(),status,s,(p-1)*s).stream().map(r->map(r,false)).toList();return new PageResult<>(list,total,p,s,(p-1)*s+list.size()<total);}
 public Map<String,Object> detail(Long id){return map(require(id),true);}
 @Transactional public Map<String,Object> cancel(Long id){ReservationRow r=require(id);if(LocalDateTime.now().isAfter(r.getReserveTime().minusMinutes(r.getCancelBeforeMinutes()==null?120:r.getCancelBeforeMinutes())))throw new IllegalArgumentException("已超过允许取消时间");if(mapper.cancelReservation(id,r.getUserId())==0)throw new IllegalArgumentException("预订当前不可取消");if(r.getSlotId()>0)mapper.releaseCapacity(r.getSlotId(),r.getPeopleCount());log(id,4,r.getStatus(),3,r.getReserveTime(),r.getReserveTime(),"用户取消",r.getUserId());return map(require(id),true);}
 @Transactional public Map<String,Object> reschedule(Long id,ReservationRescheduleRequest req){ReservationRow r=require(id);if(req.slotId()==null&&req.reserveTime()==null)throw new IllegalArgumentException("slotId 与 reserveTime 至少传一个");ReservationSlotRow slot=req.slotId()==null?null:requireSlot(req.slotId(),r.getShopId());LocalDateTime next=slot==null?req.reserveTime():LocalDateTime.of(slot.getBizDate(),slot.getStartTime());int nextStatus=slot!=null&&slot.getConfirmMode()==1?1:0;if(slot!=null&&mapper.reserveCapacity(slot.getId(),r.getPeopleCount())==0)throw new IllegalArgumentException("新时段余量不足");if(mapper.rescheduleReservation(id,r.getUserId(),slot==null?0L:slot.getId(),next,nextStatus)==0){if(slot!=null)mapper.releaseCapacity(slot.getId(),r.getPeopleCount());throw new IllegalArgumentException("预订当前不可改期");}if(r.getSlotId()>0)mapper.releaseCapacity(r.getSlotId(),r.getPeopleCount());log(id,5,r.getStatus(),nextStatus,r.getReserveTime(),next,req.reason().trim(),r.getUserId());return map(require(id),true);}
 private ReservationSlotRow requireSlot(Long id,Long shop){ReservationSlotRow s=mapper.selectSlot(id,shop,region());if(s==null)throw new NotFoundException("预订时段不存在");return s;}private ReservationRow require(Long id){UserSession u=user();ReservationRow r=mapper.selectUserReservation(id,u.userId(),region());if(r==null)throw new NotFoundException("预订不存在");return r;}private UserSession user(){UserSession u=UserSessionContext.get();if(u==null)throw new UnauthorizedException("用户登录状态不存在");return u;}private String region(){return RegionContext.getRegion().name();}
 private Map<String,Object> slotMap(ReservationSlotRow s,int people){int remain=Math.max(0,s.getCapacity()-s.getReservedCount());Map<String,Object>m=new LinkedHashMap<>();m.put("slotId",s.getId());m.put("startTime",s.getStartTime());m.put("endTime",s.getEndTime());m.put("capacity",s.getCapacity());m.put("remainingCount",remain);m.put("confirmMode",s.getConfirmMode());m.put("confirmModeText",s.getConfirmMode()==1?"自动确认":"人工确认");m.put("cancelBeforeMinutes",s.getCancelBeforeMinutes());m.put("available",remain>=people);m.put("closedReason",remain>=people?"":"余量不足");return m;}
 private Map<String,Object> map(ReservationRow r,boolean timeline){Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getId());m.put("reservationNo",r.getReservationNo());m.put("shop",Map.of("id",r.getShopId(),"name",r.getShopName(),"coverImage",r.getCoverImage(),"address",r.getAddress()));m.put("slotId",r.getSlotId());m.put("reserveTime",r.getReserveTime());m.put("peopleCount",r.getPeopleCount());m.put("contactName",r.getContactName());m.put("contactPhone",r.getContactPhone());m.put("remark",r.getRemark());m.put("status",r.getStatus());m.put("statusText",statusText(r.getStatus()));m.put("confirmMode",r.getConfirmMode());m.put("confirmModeText",r.getConfirmMode()!=null&&r.getConfirmMode()==1?"自动确认":"人工确认");m.put("rescheduleCount",r.getRescheduleCount());m.put("canCancel",r.getStatus()==0||r.getStatus()==1);m.put("canReschedule",r.getStatus()==0||r.getStatus()==1);if(timeline)m.put("timeline",mapper.selectLogs(r.getId()).stream().map(this::logMap).toList());return m;}
 private void notifyReservationCreated(ReservationRow reservation){
  if(reservation==null||reservation.getUserId()==null)return;
  String shopName=reservation.getShopName()==null||reservation.getShopName().isBlank()?"门店":reservation.getShopName();
  String reserveTimeText=reservation.getReserveTime()==null?"":reservation.getReserveTime().format(TIME_FORMATTER);
  String peopleText=reservation.getPeopleCount()==null?"":reservation.getPeopleCount()+" 人";
  boolean autoConfirmed=reservation.getStatus()!=null&&reservation.getStatus()==1;
  String title=autoConfirmed?"预订已自动确认":"预订已提交";
  String actionText=autoConfirmed?"系统已自动确认你的预订":"已提交，等待商户确认";
  String content=shopName
          +(reserveTimeText.isBlank()?"":" · "+reserveTimeText)
          +(peopleText.isBlank()?"":" · "+peopleText)
          +" · "+actionText;
  String linkUrl="/user/reservations/"+reservation.getId()+"?status="+(autoConfirmed?"confirmed":"pending");
  String region=reservation.getRegion()==null||reservation.getRegion().isBlank()?RegionContext.getRegion().name():reservation.getRegion();
  notificationService.create(reservation.getUserId(),region,RESERVATION_CREATED_TYPE,title,content,linkUrl);
 }
 private void log(Long id,int action,int from,int to,LocalDateTime oldT,LocalDateTime newT,String remark,Long userId){ReservationLogRow l=new ReservationLogRow();l.setReservationId(id);l.setActionType(action);l.setOperatorType(1);l.setOperatorId(userId);l.setFromStatus(from);l.setToStatus(to);l.setOldReserveTime(oldT);l.setNewReserveTime(newT);l.setRemark(remark);mapper.insertLog(l);}private Map<String,Object> logMap(ReservationLogRow l){Map<String,Object> m=new LinkedHashMap<>();m.put("actionType",l.getActionType());m.put("actionText",actionText(l.getActionType()));m.put("operatorType",l.getOperatorType());m.put("operatorText",operatorText(l.getOperatorType()));m.put("remark",l.getRemark()==null?"":l.getRemark());m.put("createdAt",l.getCreatedAt());return m;}private String actionText(int action){return switch(action){case 2->"商户确认";case 3->"商户拒绝";case 4->"用户取消";case 5->"用户改期";case 6->"商户改期";case 7->"确认到店";case 8->"标记爽约";case 9->"到店提醒";default->"创建预订";};}private String operatorText(Integer operatorType){if(operatorType==null)return "用户";return switch(operatorType){case 2->"商户";case 3->"系统";default->"用户";};}private String statusText(int s){return switch(s){case 1->"已确认";case 2->"已到店";case 3->"用户取消";case 4->"商户拒绝";case 5->"爽约";default->"待确认";};}}
