<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { fetchGrowthConfig, updateGrowthRule, updateLevelConfig } from '@/services/admin'
import type { GrowthRule, LevelConfig } from '@/types/admin'
const rules=ref<GrowthRule[]>([]), levels=ref<LevelConfig[]>([]), errorMessage=ref(''), successMessage=ref('')
async function load(){try{const data=await fetchGrowthConfig();rules.value=data.rules;levels.value=data.levels}catch(e){errorMessage.value=e instanceof Error?e.message:'配置加载失败'}}
async function saveRule(rule:GrowthRule){try{await updateGrowthRule(rule.id,{action:rule.action,actionName:rule.actionName,growthValue:rule.growthValue,points:rule.points,dailyLimit:rule.dailyLimit,enabled:rule.enabled});successMessage.value=`${rule.actionName} 已更新`;await load()}catch(e){errorMessage.value=e instanceof Error?e.message:'规则更新失败'}}
async function saveLevel(level:LevelConfig){try{await updateLevelConfig(level.level,{minGrowth:level.minGrowth,levelName:level.levelName,icon:level.icon,privilegeJson:level.privilegeJson,enabled:level.enabled});successMessage.value=`Lv${level.level} 已更新`;await load()}catch(e){errorMessage.value=e instanceof Error?e.message:'等级更新失败'}}
onMounted(load)
</script>
<template><section class="page-section"><div class="page-header"><div><p class="eyebrow">成长体系</p><h1>奖励权重和等级门槛都从数据库读取。</h1><p>改完只影响之后的行为，历史流水不回写，账不能越改越玄学。</p></div></div><p v-if="errorMessage" class="feedback is-error">{{errorMessage}}</p><p v-if="successMessage" class="feedback is-success">{{successMessage}}</p>
<section class="content-card"><div class="section-headline"><div><p class="eyebrow">行为奖励</p><h2>成长值 / 积分 / 每日上限</h2></div></div><div class="table-shell"><table class="data-table"><thead><tr><th>行为</th><th>成长值</th><th>积分</th><th>每日上限</th><th>启用</th><th>操作</th></tr></thead><tbody><tr v-for="rule in rules" :key="rule.id"><td><strong>{{rule.actionName}}</strong><p>{{rule.action}}</p></td><td><input v-model.number="rule.growthValue" type="number" min="0"></td><td><input v-model.number="rule.points" type="number" min="0"></td><td><input v-model.number="rule.dailyLimit" type="number" min="0"></td><td><input v-model="rule.enabled" type="checkbox"></td><td><button class="table-action" @click="saveRule(rule)">保存</button></td></tr></tbody></table></div></section>
<section class="content-card"><div class="section-headline"><div><p class="eyebrow">等级阈值</p><h2>Lv1–Lv8 配置</h2></div></div><div class="table-shell"><table class="data-table"><thead><tr><th>等级</th><th>名称</th><th>最低成长值</th><th>启用</th><th>操作</th></tr></thead><tbody><tr v-for="level in levels" :key="level.level"><td>Lv{{level.level}}</td><td><input v-model="level.levelName" type="text"></td><td><input v-model.number="level.minGrowth" type="number" min="0"></td><td><input v-model="level.enabled" type="checkbox"></td><td><button class="table-action" @click="saveLevel(level)">保存</button></td></tr></tbody></table></div></section></section></template>
