package com.tuowei.dazhongdianping.module.reservation.controller;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import java.util.UUID;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import org.springframework.transaction.annotation.Transactional;
@Transactional @SpringBootTest @AutoConfigureMockMvc class ReservationControllerTest { @Autowired MockMvc mockMvc;@Autowired ObjectMapper objectMapper;
 @Test void shouldReserveRescheduleCancelAndTrackCapacity() throws Exception {String token=register();mockMvc.perform(get("/api/c/v1/shops/10001/reservation-slots").header("X-Region","CN").param("date","2026-07-20").param("peopleCount","4")).andExpect(status().isOk()).andExpect(jsonPath("$.data.list[0].remainingCount").value(10)).andExpect(jsonPath("$.data.list[0].confirmModeText").value("自动确认"));
 MvcResult created=mockMvc.perform(post("/api/c/v1/reservations").header("Authorization",bearer(token)).header("X-Region","CN").contentType(MediaType.APPLICATION_JSON).content("{\"shopId\":10001,\"slotId\":50001,\"reserveTime\":\"2026-07-20 18:00:00\",\"peopleCount\":4,\"contactName\":\"张三\",\"contactPhone\":\"+8613812345678\",\"remark\":\"靠窗\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value(1)).andReturn();long id=objectMapper.readTree(created.getResponse().getContentAsString()).at("/data/id").asLong();
 mockMvc.perform(post("/api/c/v1/reservations/{id}/reschedule",id).header("Authorization",bearer(token)).header("X-Region","CN").contentType(MediaType.APPLICATION_JSON).content("{\"slotId\":50002,\"reserveTime\":\"2026-07-21 19:00:00\",\"reason\":\"改到明晚\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value(0)).andExpect(jsonPath("$.data.rescheduleCount").value(1));
 mockMvc.perform(get("/api/c/v1/reservations/{id}",id).header("Authorization",bearer(token)).header("X-Region","CN")).andExpect(status().isOk()).andExpect(jsonPath("$.data.timeline.length()").value(2)).andExpect(jsonPath("$.data.timeline[0].actionText").value("用户改期"));
 mockMvc.perform(post("/api/c/v1/reservations/{id}/cancel",id).header("Authorization",bearer(token)).header("X-Region","CN")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value(3));
 mockMvc.perform(get("/api/c/v1/shops/10001/reservation-slots").header("X-Region","CN").param("date","2026-07-21").param("peopleCount","4")).andExpect(status().isOk()).andExpect(jsonPath("$.data.list[0].remainingCount").value(10));}
 private String register()throws Exception{String a="reservation-"+UUID.randomUUID()+"@example.com";mockMvc.perform(post("/api/c/v1/auth/send-code").contentType(MediaType.APPLICATION_JSON).content("{\"scene\":\"register\",\"type\":\"email\",\"account\":\""+a+"\",\"deviceId\":\"reservation-test\"}")).andExpect(status().isOk());MvcResult r=mockMvc.perform(post("/api/c/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"type\":\"email\",\"account\":\""+a+"\",\"code\":\"123456\",\"password\":\"Passw0rd!\"}")).andExpect(status().isOk()).andReturn();return objectMapper.readTree(r.getResponse().getContentAsString()).at("/data/accessToken").asText();}private String bearer(String t){return "Bearer "+t;}}
